services:
  - type: web
    name: rideflow-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: rideflow-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rideflow-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: rideflow-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: rideflow-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rideflow-db
          property: password
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: rideflow-redis
          property: connectionString

  - type: keyvalue
    name: rideflow-redis

databases:
  - name: rideflow-db
